from pathlib import Path
import json,re,html,hashlib
P=Path(__file__).parent
esc=html.escape
CSS_VERSION=hashlib.sha256((P/'styles.css').read_bytes()).hexdigest()[:12]
JS_VERSION=hashlib.sha256((P/'app.js').read_bytes()).hexdigest()[:12]
data=json.loads((P/'menu.json').read_text())
data=[s for s in data if s['id'] != 'stagione']
(P/'menu.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
icons={
'leaf':'<path d="M5 21C4 9 11 3 21 3c0 10-5 17-16 18ZM5 21 17 7M10 14l-1-5m4 2 5 1"/>',
'pizza':'<path d="m4 5 8 17L22 5C16 0 9 1 4 5ZM5 8c5-3 10-3 15 0"/><circle cx="11" cy="11" r="1"/><circle cx="15" cy="14" r="1"/>',
'photo':'<rect x="3" y="5" width="18" height="15" rx="2"/><circle cx="8" cy="10" r="1.5"/><path d="m3 17 6-4 4 3 4-6 4 7"/>',
'pin':'<path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',
'play':'<path d="m9 5 11 7-11 7Z"/>',
'bag':'<path d="M5 7h14l1 14H4L5 7Zm4 0V5a3 3 0 0 1 6 0v2"/>',
'check':'<path d="m5 12 4 4L19 6"/>',
'grain':'<path d="M12 22V3m0 7C5 10 4 5 5 3c5 0 7 3 7 7Zm0 6c7 0 8-5 7-7-5 0-7 3-7 7Zm0 4c-7 0-8-5-7-7 5 0 7 3 7 7Z"/>',
'pumpkin':'<path d="M12 6c-8-5-13 14-4 15 2 1 6 1 8 0 9-1 4-20-4-15Zm0 0c-5 0-5 15 0 15s5-15 0-15Zm0 0c-1-3 0-4 2-5"/>',
'arrow':'<path d="M4 12h16m-6-6 6 6-6 6"/>'}
def ico(n):return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+icons[n]+'</svg>'
def ph(label,kind='photo',cls=''):
    return f'<div class="placeholder {cls}" role="img" aria-label="Segnaposto: {esc(label)}"><div>{ico(kind)}<span>{esc(label)}</span><small>FOTO IN ARRIVO</small></div></div>'
def head(title,desc,page='index.html'):return f'''<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{desc}"><meta name="theme-color" content="#6B3E26"><meta property="og:title" content="{title}"><meta property="og:description" content="{desc}"><meta property="og:type" content="website"><link rel="canonical" href="https://organiqsocialagency-wq.github.io/sorriso-bistrot/{page}"><meta property="og:url" content="https://organiqsocialagency-wq.github.io/sorriso-bistrot/{page}"><link rel="icon" href="img/logo-sorriso.png"><link rel="stylesheet" href="styles.css?v={CSS_VERSION}"><script src="app.js?v={JS_VERSION}" defer></script></head><body><div class="scroll-progress" aria-hidden="true"></div><a class="skip" href="#contenuto">Vai al contenuto</a>'''
def nav():return '''<header class="header"><a class="brand" href="index.html" aria-label="Sorriso Bistrot, homepage"><img src="img/logo-sorriso.png" alt="" width="56" height="56"><span>Sorriso Bistrot<small>PIZZERIA · GLUTEN FREE · ROMA</small></span></a><button class="nav-toggle" aria-expanded="false" aria-controls="nav">Menu ☰</button><nav id="nav" aria-label="Principale"><a href="index.html#pizzeria">La pizzeria</a><a href="index.html#impasti">Gli impasti</a><a href="menu.html">Il menù</a><a href="index.html#sedi">Dove siamo</a><a href="index.html#recensioni">Recensioni</a><a href="#ordina">Ordina</a><a class="button small" href="index.html#prenota">Prenota un tavolo ↗</a></nav></header>'''
def ordering():return '''<section class="wrap order-options" id="ordina" aria-label="Asporto e consegna a domicilio"><article><p class="eyebrow">RITIRO IN VIA SARNANO</p><h2>Ordina da asporto</h2><p>Indica prodotti, quantità, impasti e orario di ritiro. Invia la richiesta su WhatsApp e attendi la nostra conferma.</p><a class="button" href="index.html?servizio=asporto#prenota">Richiedi un ordine da asporto ↗</a></article><article><p class="eyebrow">DELIVEROO E JUST EAT</p><h2>Ordina a domicilio</h2><p>Scegli la piattaforma per effettuare l’ordine.</p><div class="actions"><a class="button" href="https://deliveroo.it/it/menu/Roma/roma-san-basilio/giappo-pizza-senza-glutine" target="_blank" rel="noopener noreferrer"><img class="delivery-icon" src="img/deliveroo.svg" alt="" width="26" height="26">Ordina con Deliveroo <span aria-hidden="true">↗</span></a><a class="button outline" href="https://www.justeat.it/restaurants-sorriso--gluten-free-roma/menu" target="_blank" rel="noopener noreferrer"><img class="delivery-icon" src="img/justeat.svg" alt="" width="26" height="26">Ordina con Just Eat <span aria-hidden="true">↗</span></a></div></article></section>'''
def footer():return '''<footer><div class="wrap footer-grid"><a class="brand" href="index.html"><img src="img/logo-sorriso-avorio.png" alt="Logo Sorriso" width="64" height="64"><span>Sorriso Bistrot<small>PIZZERIA · ROMA SAN BASILIO</small></span></a><p>Pizzeria con proposte senza glutine a Roma San Basilio.<br>Via Sarnano 4 · Tavoli e asporto.<br>Consegna tramite Deliveroo e Just Eat.</p><div><a href="tel:+393455834226">345 583 4226</a><br><a href="menu.html">Consulta il menù</a></div></div><div class="wrap foot-bottom"><span>© Sorriso Bistrot · Roma</span></div></footer><div class="mobile-actions"><a href="index.html#prenota">Prenota un tavolo</a><a href="index.html?servizio=asporto#prenota">Ordina d’asporto</a></div></body></html>'''
maps='https://www.google.com/maps/search/?api=1&query=Sorriso+Bistrot+Via+Sarnano+4+Roma'
review_source='https://restaurantguru.com/Junior-Pizza-Chef-Gluten-Free-Roma-Rome-2'
s=head('Pizzeria senza glutine Roma San Basilio | Sorriso Bistrot','Pizza senza glutine a Roma San Basilio: laboratorio separato e basi preparate da noi. Consulta menù e prezzi, richiedi un tavolo o ordina da asporto.')+nav()
s+='''<main id="contenuto"><section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span> SORRISO BISTROT · ROMA, SAN BASILIO</p><h1><span class="hero-title-main">Pizza <em>senza glutine</em></span><span class="hero-title-top">a Roma, a San Basilio</span></h1><p class="lead">Da Sorriso Bistrot prepariamo le basi nel nostro laboratorio gluten free separato, senza usare basi precotte. Nel menù trovi pizze, fritti e dolci senza glutine.</p><div class="actions"><a class="button" href="#prenota">Prenota un tavolo ↗</a><a class="button outline" href="menu.html">Visualizza Menù ↗</a></div><div class="hero-notes"><span>Via Sarnano 4, Roma</span><span>Asporto</span><span>Consegna a domicilio</span></div></div><div class="video-area awaiting-video"><div class="video-frame" aria-roledescription="carosello" aria-label="Video di Sorriso Bistrot"><div class="video-top"><span>DENTRO SORRISO</span><span id="video-count">01 / 03</span></div>'''
for i,(title,sub) in enumerate([('Come prepariamo le basi','Il laboratorio senza glutine.'),('La cottura delle pizze','Dal laboratorio al forno.'),('La sala di Via Sarnano','Il locale a Roma San Basilio.')]):
    s+=f'<div class="video-slide" data-slide="{i}" {"hidden" if i else ""}><div class="video-placeholder">{ico("grain" if i==0 else "pizza" if i==1 else "leaf")}<span>VIDEO IN ARRIVO</span></div><video controls playsinline preload="none" hidden aria-label="{title}"></video><div class="video-caption"><h2>{title}</h2><p>{sub}</p></div></div>'
s+='''<div class="video-controls"><div class="dots" aria-label="Scegli video"><button class="selected" aria-label="Video 1: Come prepariamo le basi" aria-pressed="true" data-video="0">01</button><button aria-label="Video 2: La cottura delle pizze" aria-pressed="false" data-video="1">02</button><button aria-label="Video 3: La sala di Via Sarnano" aria-pressed="false" data-video="2">03</button></div><button class="rotation" aria-label="Metti in pausa la rotazione">Ⅱ</button></div></div></div></section>'''
s+=f'''<section id="pizzeria" class="wrap section split">{ph('La pizzeria · Via Sarnano',cls='restaurant-photo')}<div><p class="eyebrow">BENVENUTI DA SORRISO</p><h2>Sorriso Bistrot,<br>in <em>Via Sarnano</em></h2><p>Sorriso Bistrot è una pizzeria in Via Sarnano 4, nel quartiere San Basilio a Roma. Proponiamo pizze con impasto classico e senza glutine, da mangiare al tavolo o da ordinare per l’asporto e la consegna a domicilio.</p><p>Le basi senza glutine vengono preparate nel nostro laboratorio separato. Il menù comprende anche fritti e dolci senza glutine: consulta le proposte e segnala eventuali allergie quando prenoti o ordini.</p><a class="text-link" href="menu.html">Consulta il menù {ico('arrow')}</a></div></section>'''
s+='''<section id="impasti" class="section tinted"><div class="wrap dough-pin"><div class="section-head"><p class="eyebrow">GLI IMPASTI SENZA GLUTINE</p><h2>Riso, zucca<br>e <em>canapa</em></h2><p>Scegli l’impasto per la tua pizza tra le proposte disponibili.</p></div><div class="three-grid doughs">'''
for num,name,kind,desc in [('01','Riso','grain','Una delle tre proposte di impasto senza glutine. Consulta il menù per scegliere gli ingredienti della tua pizza.'),('02','Zucca','pumpkin','Un’alternativa al riso per la tua pizza senza glutine. Chiedi allo staff gli abbinamenti e la disponibilità.'),('03','Canapa','leaf','Disponibile tra le varianti di impasto senza glutine. Consulta il menù per prezzi e supplementi.')]:
    s+=f'<article class="dough"><div class="dough-picture">{ph("Impasto: "+name.lower(),kind)}<span class="number">{num}</span></div><div class="dough-copy"><p class="eyebrow">IMPASTO SENZA GLUTINE</p><h3>{name}</h3><p>{desc}</p><a href="menu.html" class="text-link">Consulta le pizze ↗</a></div></article>'
s+='''</div><div class="dough-progress" aria-label="Scegli impasto"><button type="button" data-dough="0" aria-pressed="true">01 · Riso</button><button type="button" data-dough="1" aria-pressed="false">02 · Zucca</button><button type="button" data-dough="2" aria-pressed="false">03 · Canapa</button></div><p class="fine center">Indica l’impasto che preferisci quando ordini. Lo staff ti confermerà la disponibilità.</p></div></section>'''
s+='''<section class="section wrap" id="menu"><div class="menu-intro"><div><p class="eyebrow">IL NOSTRO MENÙ</p><h2>Menù e <em>prezzi</em></h2></div><div><p>Consulta pizze, fritti e dolci, con ingredienti, allergeni indicati e prezzi. Per le pizze puoi confrontare il listino classico e quello senza glutine.</p><a class="button" href="menu.html">Visualizza menù ↗</a></div></div><div class="three-grid menu-teasers">'''
for name,sub,cat in [('Pizze','Ingredienti e prezzi','pizze'),('Fritti','Consulta le proposte','antipasti'),('Dolci','Le proposte senza glutine','dolci')]:s+=f'<a class="teaser" href="menu.html?categoria={cat}">{ph(name,"pizza" if cat=="pizze" else "photo")}<div><h3>{name}</h3><span>↗</span><p>{sub}</p></div></a>'
s+='</div></section>'
s+=f'''<section class="section reviews" id="recensioni"><div class="wrap"><div class="section-head"><p class="eyebrow">Le vostre recensioni</p><h2>Chi viene per la pizza,<br>torna con <em>il sorriso</em></h2><p>Estratti di recensioni Google riportati da Restaurant Guru.</p></div><div class="reviews-marquee"><div class="reviews-row"><div class="reviews-track">'''
# 23 quoted words total from the secondary source.
for name,quote in [('Marcello Passerini','Veramente la migliore pizzeria di Roma e dintorni'),('Silvia La Torre','Personale e proprietario gentilissimi.'),('Carlo Giuseppe Bertinetto','Best gluten free pizza I have had.')]:
    rating=5 if name in ('Marcello Passerini','Silvia La Torre') else None
    stars=f'<div class="review-stars" role="img" aria-label="Valutazione: {rating} su 5 stelle"><span aria-hidden="true">'+('★'*rating)+'</span></div>' if rating else ''
    s+=f'<article class="review">{stars}<span class="quote-mark">“</span><blockquote>{quote}</blockquote><div class="review-author"><span class="avatar">{name[0]}</span><div><b>{name}</b><small>Recensione Google · estratto</small></div></div><a href="{review_source}" target="_blank" rel="noopener">Leggi su Restaurant Guru ↗</a></article>'
s+=f'''</div></div></div><p class="fine center">Estratti consultati il 18 settembre 2026.</p><div class="center"><a class="text-link" href="{maps}" target="_blank" rel="noopener">Trova Sorriso su Google Maps ↗</a></div></div></section>'''
s+='''<section class="section wrap compare-section" id="differenza"><div class="section-head"><p class="eyebrow">IL LABORATORIO E IL MENÙ</p><h2>Come prepariamo<br>il nostro <em>senza glutine</em></h2><p>Dalla preparazione delle basi alla scelta sul menù: ecco cosa trovi da Sorriso.</p></div><div class="comparison comparison-cards"><article class="compare-before"><span class="compare-tag">Quello che cerchi</span><ul class="compare-list">'''
for point in ['Capire dove vengono preparate le basi senza glutine','Evitare le basi precotte','Poter scegliere l’impasto','Ordinare anche oltre la pizza','Confrontare le proposte prima di ordinare']:
    s+=f'<li><span class="compare-need" aria-hidden="true">→</span><strong>{point}</strong></li>'
s+='''</ul></article><article class="compare-after"><div class="compare-card-top"><span class="compare-tag">Da Sorriso</span><img src="img/logo-sorriso.png" alt="Sorriso Bistrot" width="64" height="64" loading="lazy"></div><ul class="compare-list">'''
for point in ['Laboratorio gluten free separato','Basi preparate da noi, mai precotte','Riso, zucca e canapa, secondo disponibilità','Fritti e dolci senza glutine nel menù','Menù online con ingredienti e prezzi']:
    s+=f'<li>{ico("check")}<strong>{point}</strong></li>'
s+='''</ul><a class="text-link" href="menu.html">Visualizza Menù ↗</a></article></div><p class="fine center">Proponiamo anche pizze con glutine. Le basi senza glutine vengono preparate in un laboratorio separato. Segnala celiachia e altre allergie quando prenoti o ordini.</p></section>'''
s+=ordering()
s+='''<section id="prenota" class="section booking"><div class="wrap split"><div><p class="eyebrow">PRENOTAZIONI E ASPORTO</p><h2 id="booking-title">Richiedi <em>un tavolo</em></h2><p id="booking-intro">Compila il modulo e invia il messaggio su WhatsApp. Ti risponderemo per confermare la disponibilità.</p><p>La richiesta è confermata solo dopo la risposta dello staff.</p><a class="text-link" href="tel:+393455834226">Preferisci chiamare? 345 583 4226 ↗</a></div><form id="booking-form" class="booking-form"><div class="service-tabs" aria-label="Tipo di prenotazione"><button type="button" data-service="tavolo" aria-pressed="true">Tavolo</button><button type="button" data-service="asporto" aria-pressed="false">Asporto</button></div><input type="hidden" name="servizio" value="tavolo"><div class="form-grid"><label>Il tuo nome<input name="nome" autocomplete="name" required maxlength="80" placeholder="Come ti chiami?"></label><label>Telefono<input name="telefono" type="tel" autocomplete="tel" required pattern="[+0-9 ()-]{7,20}" placeholder="Il tuo numero"></label><label>Data<input name="data" type="date" required></label><label>Orario<select name="ora" required><option value="">Scegli l’orario</option><option>18:00</option><option>18:30</option><option>19:00</option><option>19:30</option><option>20:00</option><option>20:30</option><option>21:00</option><option>21:30</option><option>22:00</option><option>22:30</option></select></label><label id="people-field">Persone<select name="persone"><option>2 persone</option><option>1 persona</option><option>3 persone</option><option>4 persone</option><option>5 persone</option><option>6 persone</option><option>7 persone</option><option>8 persone</option><option>Più di 8 persone</option></select></label><label class="wide"><span id="note-label">Allergie, esigenze alimentari o altre richieste (facoltativo)</span><textarea name="note" rows="3" maxlength="1200" placeholder="Indica eventuali allergie o altre esigenze"></textarea></label></div><p class="fine">I dati del modulo non vengono salvati su questo sito. Il pulsante prepara un messaggio su WhatsApp: sarai tu a inviarlo al locale.</p><button class="button full" type="submit">Prepara richiesta tavolo ↗</button><p id="form-message" role="status"></p><a id="send-request" class="button full" hidden target="_blank" rel="noopener">Continua su WhatsApp ↗</a></form></div></section>'''
s+=f'''<section id="sedi" class="section wrap split"><div><p class="eyebrow">DOVE SIAMO</p><h2>Sorriso Bistrot,<br><em>Roma San Basilio</em></h2><div class="address"><h3>Via Sarnano</h3><p>Via Sarnano 4 · 00156 Roma<br><a href="tel:+393455834226">345 583 4226</a></p><p>Martedì – domenica · 18:00–23:00<br>Lunedì · chiuso</p></div><div class="actions"><a class="button" href="{maps}" target="_blank" rel="noopener">Indicazioni su Google Maps ↗</a><a class="text-link" href="tel:+393455834226">Chiama</a></div></div><div class="location-map"><iframe title="Google Maps — Sorriso Bistrot, Via Sarnano 4, Roma" src="https://www.google.com/maps?q=Via%20Sarnano%204%2C%2000156%20Roma&amp;z=16&amp;output=embed" width="600" height="450" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><a href="{maps}" target="_blank" rel="noopener">Apri in Google Maps ↗<span>Via Sarnano 4 · Roma</span></a></div></section>'''
# Social video links and optional local posters are configured independently of page copy.
socials=json.loads((P/'social-videos.json').read_text())
s+='<section id="social" class="section social-section"><div class="wrap"><div class="section-head"><p class="eyebrow">TIKTOK · INSTAGRAM · FACEBOOK</p><h2>Seguici sui <em>social</em></h2><p>Guarda i nostri video per scoprire le promozioni, le offerte e le novità di Sorriso.</p></div><div class="social-tabs" aria-label="Scegli un social">'
for social in socials:
    s+=f'<a class="social-tab" href="#social-{social["id"]}">{esc(social["name"])}</a>'
s+='</div>'
for social in socials:
    sid=social['id'];name=esc(social['name'])
    s+=f'<div class="social-panel" id="social-{sid}" aria-labelledby="social-title-{sid}"><div class="social-panel-head"><h3 id="social-title-{sid}">{name}</h3>'
    if social['profile']:
        s+=f'<a class="text-link" href="{esc(social["profile"])}" target="_blank" rel="noopener noreferrer">Seguici su {name} ↗</a>'
    s+=f'</div><div class="social-track" id="social-track-{sid}" tabindex="0" aria-label="Video {name}">'
    for i in range(max(3,len(social['videos']))):
        video=social['videos'][i] if i<len(social['videos']) else None
        if video:
            poster=f'<img src="{esc(video["poster"])}" alt="" loading="lazy" width="360" height="480">' if video.get('poster') else ico('play')
            s+=f'<a class="social-video" href="{esc(video["url"])}" target="_blank" rel="noopener noreferrer"><div class="social-poster">{poster}<span class="social-platform">{name}</span></div><div class="social-video-copy"><h4>{esc(video["title"])}</h4><span>Guarda su {name} ↗</span></div></a>'
        else:
            s+=f'<article class="social-video is-placeholder" aria-label="Spazio per il video {i+1} di {name}"><div class="social-poster"><span class="social-platform">{name}</span><span class="social-placeholder-mark" aria-hidden="true">{i+1:02d}</span><span class="social-coming">Video in arrivo</span></div><div class="social-video-copy"><p>I video di Sorriso su {name}</p></div></article>'
    s+=f'</div><div class="social-carousel-controls" hidden><button type="button" data-social-step="-1" aria-controls="social-track-{sid}" aria-label="Video precedenti su {name}">←</button><span>Scorri i video</span><button type="button" data-social-step="1" aria-controls="social-track-{sid}" aria-label="Video successivi su {name}">→</button></div></div>'
s+='</div></section>'
s+='''<section class="wrap faq"><p class="eyebrow">PRIMA DI VENIRE A TROVARCI</p><h2>Domande <em>frequenti</em></h2><details><summary>Dove si trova Sorriso Bistrot?</summary><p>Sorriso Bistrot si trova in Via Sarnano 4, nel quartiere San Basilio a Roma. Puoi mangiare al tavolo oppure richiedere un ordine da asporto.</p></details><details><summary>Il locale propone solo prodotti senza glutine?</summary><p>No, proponiamo anche pizze con impasto classico contenente glutine. Le basi senza glutine vengono preparate in un laboratorio separato. Segnala celiachia e altre allergie quando prenoti o ordini.</p></details><details><summary>Come prenoto un tavolo o una pizza da asporto?</summary><p>Usa il modulo per preparare la richiesta su WhatsApp o chiama il 345 583 4226. Per l’asporto indica prodotti, quantità e impasti. Attendi sempre la conferma dello staff.</p></details><details><summary>Ci sono anche fritti e dolci senza glutine?</summary><p>Sì, il menù include antipasti e dolci gluten free. Consulta la pagina menù per prodotti, prezzi e allergeni e verifica le disponibilità con lo staff.</p></details><details><summary>Usate basi senza glutine precotte?</summary><p>No. Prepariamo le basi nel nostro laboratorio gluten free separato, senza usare basi precotte.</p></details><details><summary>Come ordino a domicilio?</summary><p>Puoi ordinare su <a href="https://deliveroo.it/it/menu/Roma/roma-san-basilio/giappo-pizza-senza-glutine" target="_blank" rel="noopener">Deliveroo</a> o <a href="https://www.justeat.it/restaurants-sorriso--gluten-free-roma/menu" target="_blank" rel="noopener">Just Eat</a>. Scegli la piattaforma e completa l’ordine sul suo sito o nella sua app.</p></details></section></main>'''
schema={'@context':'https://schema.org','@type':'Restaurant','name':'Sorriso Bistrot','servesCuisine':['Pizza','Italiana','Senza glutine'],'telephone':'+393455834226','address':{'@type':'PostalAddress','streetAddress':'Via Sarnano 4','postalCode':'00156','addressLocality':'Roma','addressCountry':'IT'}}
schema.update({'url':'https://organiqsocialagency-wq.github.io/sorriso-bistrot/index.html','menu':'https://organiqsocialagency-wq.github.io/sorriso-bistrot/menu.html','openingHoursSpecification':[{'@type':'OpeningHoursSpecification','dayOfWeek':['Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],'opens':'18:00','closes':'23:00'}]})
s+='<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False)+'</script>'+footer()
(P/'index.html').write_text(s)
# Full menu: prerender products so content and prices are available without JavaScript.
s=head('Menù pizza senza glutine a Roma | Sorriso Bistrot','Consulta tutti i prodotti e i prezzi del menù Sorriso Bistrot: pizza gluten free e classica, fritti, calzoni, primi, dolci e bevande. Via Sarnano, Roma.','menu.html')+nav()
s+='''<main id="contenuto"><section class="wrap menu-page-head"><p class="eyebrow">SORRISO BISTROT · VIA SARNANO, ROMA</p><h1>Il menù di <em>Sorriso Bistrot</em></h1><p>Pizze, fritti, dolci e bevande, con ingredienti e prezzi. Per le pizze scegli il listino classico o senza glutine.</p><div class="actions"><a class="button" href="index.html#prenota">Prenota un tavolo ↗</a><a class="button outline" href="index.html?servizio=asporto#prenota">Ordina d’asporto ↗</a><a class="text-link" href="Sorriso-Menu-IT.pdf">Scarica il menù PDF ↓</a></div></section>'''+ordering()+'''<section class="wrap menu-catalog"><div class="catalog-tools"><label>Cerca nel menù<input id="search-menu" type="search" placeholder="Margherita, supplì, pistacchio…"></label><label>Categoria<select id="category"><option value="tutte">Tutte le categorie</option>'''
for cat in data:s+=f'<option value="{cat["id"]}">{esc(cat["t"])}</option>'
s+='''</select></label><label>Listino pizze<select id="price-mode"><option value="gf">Senza glutine</option><option value="classica">Classica (con glutine)</option></select></label></div><p class="fine">Il selettore cambia il prezzo delle preparazioni con doppio listino. Non è un filtro allergeni; per le bevande consulta le indicazioni GF.</p><p id="result-count" role="status"></p><p id="empty-menu" hidden>Nessun prodotto trovato. Prova un altro ingrediente o seleziona tutte le categorie.</p>'''
for cat in data:
    s+=f'<section class="menu-category" data-category="{cat["id"]}"><div class="category-heading"><h2>{esc(cat["t"])}</h2><span>{len(cat["items"]):02d} proposte</span></div><div class="product-grid">'
    for it in cat['items']:
        n=it['n'];d=it['d'];pc=it['pc'];pg=it['pg']
        s+=f'<article class="product" data-search="{esc((n+" "+d).lower())}">{ph(n)}<div class="product-copy"><h3>{esc(n)}</h3><p>{esc(d)}</p><p class="allergens">Allergeni: {esc(it["a"]) if it["a"] else "chiedere allo staff"}</p><div class="product-price"><b data-classica="{esc(pc)}" data-gf="{esc(pg or pc)}">{esc(pg or pc)}</b><span>{"senza glutine" if pg else ""}</span></div></div></article>'
    s+='</div></section>'
s+='''</section><section class="wrap menu-notes"><h2>Ingredienti e allergeni</h2><p>1 Glutine · 2 Crostacei · 3 Uova · 4 Pesce · 5 Arachidi · 6 Soia · 7 Latte · 8 Frutta a guscio · 9 Sedano · 10 Senape · 11 Sesamo · 12 Anidride solforosa e solfiti · 13 Lupino · 14 Molluschi.</p><p>L’impasto classico contiene glutine. Le indicazioni sono riprese dal menù fornito; in caso di celiachia o allergie chiedi conferma al personale prima di ordinare. Il menù di origine riporta la possibile presenza di tracce per contaminazione.</p><p>Extra: ingrediente €1 · salsiccia €1,50 · prosciutto €2 · cornicione ricotta €2 · senza lattosio €1,50 · impasto canapa bio €2. Verifica le varianti disponibili con il locale.</p><a class="button" href="index.html?servizio=asporto#prenota">Ordina d’asporto ↗</a></section></main>'''+footer()
(P/'menu.html').write_text(s)
print('Generated homepage and menu:',sum(len(x['items']) for x in data),'products')
