from pathlib import Path
import json,re,html,hashlib
P=Path(__file__).parent
esc=html.escape
CSS_VERSION=hashlib.sha256((P/'styles.css').read_bytes()).hexdigest()[:12]
JS_VERSION=hashlib.sha256((P/'app.js').read_bytes()).hexdigest()[:12]
data=json.loads((P/'menu.json').read_text())
data=[s for s in data if s['id'] != 'stagione']
(P/'menu.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
icons={
'leaf':'<path d="M5 21C4 9 11 3 21 3c0 10-5 17-16 18ZM5 21 17 7M10 14l-1-5m4 2 5 1"/>',
'pizza':'<path d="m4 5 8 17L22 5C16 0 9 1 4 5ZM5 8c5-3 10-3 15 0"/><circle cx="11" cy="11" r="1"/><circle cx="15" cy="14" r="1"/>',
'photo':'<rect x="3" y="5" width="18" height="15" rx="2"/><circle cx="8" cy="10" r="1.5"/><path d="m3 17 6-4 4 3 4-6 4 7"/>',
'pin':'<path d="M19 10c0 5-7 12-7 12S5 15 5 10a7 7 0 1 1 14 0Z"/><circle cx="12" cy="10" r="2"/>',
'play':'<path d="m9 5 11 7-11 7Z"/>',
'bag':'<path d="M5 7h14l1 14H4L5 7Zm4 0V5a3 3 0 0 1 6 0v2"/>',
'check':'<path d="m5 12 4 4L19 6"/>',
'grain':'<path d="M12 22V3m0 7C5 10 4 5 5 3c5 0 7 3 7 7Zm0 6c7 0 8-5 7-7-5 0-7 3-7 7Zm0 4c-7 0-8-5-7-7 5 0 7 3 7 7Z"/>',
'pumpkin':'<path d="M12 6c-8-5-13 14-4 15 2 1 6 1 8 0 9-1 4-20-4-15Zm0 0c-5 0-5 15 0 15s5-15 0-15Zm0 0c-1-3 0-4 2-5"/>',
'arrow':'<path d="M4 12h16m-6-6 6 6-6 6"/>'}
def ico(n):return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.3" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'+icons[n]+'</svg>'
def ph(label,kind='photo',cls=''):
    return f'<div class="placeholder {cls}" role="img" aria-label="Segnaposto: {esc(label)}"><div>{ico(kind)}<span>{esc(label)}</span><small>FOTO IN ARRIVO</small></div></div>'
def head(title,desc):return f'''<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{desc}"><meta name="theme-color" content="#6B3E26"><meta property="og:title" content="{title}"><meta property="og:description" content="{desc}"><meta property="og:type" content="website"><link rel="icon" href="img/logo-sorriso.png"><link rel="stylesheet" href="styles.css?v={CSS_VERSION}"><script src="app.js?v={JS_VERSION}" defer></script></head><body><div class="scroll-progress" aria-hidden="true"></div><a class="skip" href="#contenuto">Vai al contenuto</a>'''
def nav():return '''<header class="header"><a class="brand" href="index.html" aria-label="Sorriso Bistrot, homepage"><img src="img/logo-sorriso.png" alt="" width="56" height="56"><span>Sorriso Bistrot<small>PIZZERIA · GLUTEN FREE · ROMA</small></span></a><button class="nav-toggle" aria-expanded="false" aria-controls="nav">Menu ☰</button><nav id="nav" aria-label="Principale"><a href="index.html#pizzeria">La pizzeria</a><a href="index.html#impasti">Gli impasti</a><a href="menu.html">Il menù</a><a href="index.html#sedi">Dove siamo</a><a href="index.html#recensioni">Recensioni</a><a href="#ordina">Ordina</a><a class="button small" href="index.html#prenota">Prenota un tavolo ↗</a></nav></header>'''
def ordering():return '''<section class="wrap order-options" id="ordina" aria-label="Asporto e consegna a domicilio"><article><p class="eyebrow">RITIRO IN VIA SARNANO</p><h2>Ordina d’asporto</h2><p>Scegli dal menù e comunicaci prodotti, quantità e orario di ritiro.</p><a class="button" href="index.html?servizio=asporto#prenota">Ordina d’asporto ↗</a></article><article><p class="eyebrow">SORRISO, ANCHE A CASA TUA</p><h2>Ordina a domicilio</h2><p>Ricevi il tuo ordine con Deliveroo o Just Eat. Scegli la piattaforma che preferisci.</p><div class="actions"><a class="button" href="https://deliveroo.it/it/menu/Roma/roma-san-basilio/giappo-pizza-senza-glutine" target="_blank" rel="noopener noreferrer">Ordina con Deliveroo ↗</a><a class="button outline" href="https://www.justeat.it/restaurants-sorriso--gluten-free-roma/menu" target="_blank" rel="noopener noreferrer">Ordina con Just Eat ↗</a></div><p class="fine">Disponibilità, zone di consegna e costi sono indicati sulla piattaforma.</p></article></section>'''
def footer():return '''<footer><div class="wrap footer-grid"><a class="brand" href="index.html"><img src="img/logo-sorriso-avorio.png" alt="Logo Sorriso" width="64" height="64"><span>Sorriso Bistrot<small>IL GUSTO DI STARE BENE.</small></span></a><p>Pizza, passione e momenti da condividere.<br>Via Sarnano 4, 00156 Roma</p><div><a href="tel:+393455834226">345 583 4226</a><br><a href="menu.html">Consulta il menù</a></div></div><div class="wrap foot-bottom"><span>© Sorriso Bistrot · Roma</span><span>Caldo. Autentico. Accogliente.</span></div></footer><div class="mobile-actions"><a href="index.html#prenota">Prenota un tavolo</a><a href="index.html?servizio=asporto#prenota">Ordina d’asporto</a></div></body></html>'''
maps='https://www.google.com/maps/search/?api=1&query=Sorriso+Bistrot+Via+Sarnano+4+Roma'
review_source='https://restaurantguru.com/Junior-Pizza-Chef-Gluten-Free-Roma-Rome-2'
s=head('Pizzeria senza glutine a Roma | Sorriso Bistrot – Via Sarnano','Pizza senza glutine a Roma San Basilio: scopri gli impasti di riso, zucca e canapa, consulta il menù e richiedi un tavolo o il tuo asporto da Sorriso Bistrot.')+nav()
s+='''<main id="contenuto"><section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="dot"></span> SORRISO BISTROT · ROMA, SAN BASILIO</p><h1><span class="hero-title-top">La tua pizzeria <em>senza glutine</em> a Roma.</span><span class="hero-title-main">Il gusto di stare <em>insieme.</em></span></h1><p class="lead">Il piacere di stare a tavola, tutti insieme. Pizza senza glutine, impasti da scoprire e l’accoglienza di chi è felice di averti qui.</p><div class="actions"><a class="button" href="#prenota">Prenota ora un tavolo ↗</a><a class="button outline" href="menu.html">Visualizza Menù ↗</a></div><div class="hero-notes"><span>Pizza gluten free</span><span>Riso, zucca e canapa</span><span>Via Sarnano, Roma</span></div></div><div class="video-area"><div class="video-frame" aria-roledescription="carosello" aria-label="Video di Sorriso Bistrot"><div class="video-top"><span>DENTRO SORRISO</span><span id="video-count">01 / 03</span></div>'''
for i,(title,sub) in enumerate([('Le mani in pasta','Dove comincia ogni sorriso.'),('Il forno, la passione','Il nostro modo di fare pizza.'),('La tua prossima serata','Un posto a tavola, anche per te.')]):
    s+=f'<div class="video-slide" data-slide="{i}" {"hidden" if i else ""}><div class="video-placeholder">{ico("grain" if i==0 else "pizza" if i==1 else "leaf")}<span>VIDEO IN ARRIVO</span></div><video controls playsinline preload="none" hidden aria-label="{title}"></video><div class="video-caption"><h2>{title}</h2><p>{sub}</p></div></div>'
s+='''<div class="video-controls"><div class="dots" aria-label="Scegli video"><button class="selected" aria-label="Video 1: Le mani in pasta" aria-pressed="true" data-video="0">01</button><button aria-label="Video 2: Il forno, la passione" aria-pressed="false" data-video="1">02</button><button aria-label="Video 3: La tua prossima serata" aria-pressed="false" data-video="2">03</button></div><button class="rotation" aria-label="Metti in pausa la rotazione">Ⅱ</button></div></div><p class="handwritten">Più di una pizza. Un momento insieme.</p></div></section><div class="ribbon"><span>IL PIACERE DI SCEGLIERE</span><b>Senza glutine</b><i>✧</i><b>Con carattere</b><i>✧</i><b>Da condividere</b><span>FATTO PER STARE BENE</span></div>'''
s+=f'''<section id="pizzeria" class="wrap section split">{ph('La pizzeria · Via Sarnano',cls='restaurant-photo')}<div><p class="eyebrow">BENVENUTI DA SORRISO</p><h2>La buona pizza<br>unisce. <em>Sempre.</em></h2><p>A Roma, in Via Sarnano, Sorriso Bistrot è il posto per ritrovarsi davanti a una buona pizza. Con gli amici, in famiglia, con chi vuoi tu.</p><p>Il senza glutine è parte della nostra identità: dalle pizze ai fritti, fino ai dolci. Scopri le proposte gluten free nel menù e raccontaci le tue esigenze al momento della prenotazione.</p><a class="text-link" href="menu.html">Scopri cosa portiamo a tavola {ico('arrow')}</a><div class="little-note">{ico('leaf')} Ingredienti semplici. Grandi momenti.</div></div></section>'''
s+='''<section id="impasti" class="section tinted"><div class="wrap dough-pin"><div class="section-head"><p class="eyebrow">LE FARINE · PERCHÉ SCEGLIERCI</p><h2>Tre impasti.<br>Un mondo di <em>gusto.</em></h2><p>Il senza glutine ha tante sfumature. Trova quella che ti somiglia.</p></div><div class="three-grid doughs">'''
for num,name,kind,tag,desc,advantages in [('01','Riso','grain','IL GUSTO DELLA SEMPLICITÀ','Una base dal gusto delicato, per lasciare spazio al pomodoro, alla mozzarella e ai tuoi ingredienti preferiti.',['Sapore delicato','Versatile negli abbinamenti','Per chi ama le classiche']),('02','Zucca','pumpkin','IL LATO DORATO DELLA PIZZA','Colore caldo e una nota dolce: un incontro da provare con ingredienti sapidi e abbinamenti di carattere.',['Una nota dolce','Colore naturalmente caldo','Da abbinare a sapori decisi']),('03','Canapa','leaf','UN CARATTERE TUTTO SUO','Un gusto rustico e una personalità riconoscibile. La scelta per chi cerca qualcosa di diverso, anche senza glutine.',['Gusto rustico','Abbinamenti gourmet','Un’alternativa da scoprire'])]:
    s+=f'<article class="dough"><div class="dough-picture">{ph("Farina di "+name.lower(),kind)}<span class="number">{num}</span></div><div class="dough-copy"><p class="eyebrow">{tag}</p><h3>{name}</h3><p>{desc}</p><ul>'+''.join(f'<li>{ico("check")}{v}</li>' for v in advantages)+'</ul><a href="menu.html" class="text-link">Trova la tua pizza ↗</a></div></article>'
s+='''</div><div class="dough-progress" aria-label="Scegli impasto"><button type="button" data-dough="0" aria-pressed="true">01 · Riso</button><button type="button" data-dough="1" aria-pressed="false">02 · Zucca</button><button type="button" data-dough="2" aria-pressed="false">03 · Canapa</button></div><p class="fine center">Chiedi allo staff quali impasti sono disponibili e quali abbinamenti puoi scegliere.</p></div></section>'''
s+='''<section class="section wrap" id="menu"><div class="menu-intro"><div><p class="eyebrow">IL NOSTRO MENÙ</p><h2>La parte più bella?<br><em>Scegliere.</em></h2></div><div><p>Le classiche che ami, le pizze gourmet che ti sorprendono, i fritti da condividere e un dolce per finire. Tutti i prodotti, gli ingredienti e i prezzi in un unico menù.</p><a class="button" href="menu.html">Visualizza menù completo ↗</a></div></div><div class="three-grid menu-teasers">'''
for name,sub,cat in [('Le pizze','Classiche, speciali e gourmet','pizze'),('I fritti','Il modo migliore di cominciare','antipasti'),('I dolci','Un ultimo, dolcissimo sorriso','dolci')]:s+=f'<a class="teaser" href="menu.html?categoria={cat}">{ph(name,"pizza" if cat=="pizze" else "photo")}<div><h3>{name}</h3><span>↗</span><p>{sub}</p></div></a>'
s+='</div></section>'
s+=f'''<section class="section reviews" id="recensioni"><div class="wrap"><div class="section-head"><p class="eyebrow">Le vostre recensioni</p><h2>Chi viene per la pizza,<br>torna con <em>il sorriso</em></h2><p>Recensioni reali pubblicate su Google</p></div><div class="reviews-marquee"><div class="reviews-row"><div class="reviews-track">'''
# 23 quoted words total from the secondary source.
for name,quote in [('Marcello Passerini','Veramente la migliore pizzeria di Roma e dintorni'),('Silvia La Torre','Personale e proprietario gentilissimi.'),('Carlo Giuseppe Bertinetto','Best gluten free pizza I have had.')]:
    s+=f'<article class="review"><span class="quote-mark">“</span><blockquote>{quote}</blockquote><div class="review-author"><span class="avatar">{name[0]}</span><div><b>{name}</b><small>Recensione Google · estratto</small></div></div><a href="{review_source}" target="_blank" rel="noopener">Leggi la fonte ↗</a></article>'
s+=f'''</div></div></div><p class="fine center">Estratti Google riportati da Restaurant Guru, consultati il 18 settembre 2026. Non è un feed in tempo reale.</p><div class="center"><a class="text-link" href="{maps}" target="_blank" rel="noopener">Trova Sorriso su Google Maps ↗</a></div></div></section>'''
s+='''<section class="section wrap compare-section" id="differenza"><div class="section-head"><p class="eyebrow">IL SENZA GLUTINE, COME LO INTENDIAMO NOI</p><h2>Da un’alternativa<br>a una <em>vera scelta.</em></h2><p>Il gluten free degli altri? Ogni cucina ha il suo modo di lavorare.<br>Ecco cosa cercare e cosa trovi da Sorriso.</p></div><div class="comparison comparison-cards"><article class="compare-before"><span class="compare-tag">Quando scegli un locale</span><h3>Una pizza senza glutine.<br>Ma quali possibilità?</h3><ul class="compare-list">'''
for title,body in [('La scelta','Quali pizze del menù sono disponibili senza glutine?'),('L’impasto','Puoi scegliere tra impasti diversi?'),('La serata','Ci sono anche fritti e dolci gluten free?'),('La chiarezza','Puoi consultare prezzi, ingredienti e allergeni?')]:
    s+=f'<li><span class="compare-question" aria-hidden="true">?</span><div><strong>{title}</strong><p>{body}</p></div></li>'
s+='''</ul></article><article class="compare-after"><div class="compare-card-top"><span class="compare-tag">Da Sorriso</span><img src="img/logo-sorriso.png" alt="Sorriso Bistrot" width="64" height="64" loading="lazy"></div><h3>Il piacere di scegliere.<br>Il gusto di stare insieme.</h3><ul class="compare-list">'''
for title,body in [('Le pizze che ami','Classiche, speciali e gourmet con listino gluten free.'),('Tre gusti da scoprire','Riso, zucca e canapa, secondo disponibilità.'),('Dall’antipasto al dolce','Fritti e dolci senza glutine presenti nel menù.'),('Tutto a portata di mano','Prezzi e allergeni consultabili; lo staff risponde alle tue esigenze.')]:
    s+=f'<li>{ico("check")}<div><strong>{title}</strong><p>{body}</p></div></li>'
s+='''</ul><a class="text-link" href="menu.html">Visualizza Menù ↗</a></article></div><p class="fine center">In sede proponiamo anche impasti con glutine. Per celiachia e allergie contatta lo staff prima di ordinare.</p></section>'''
s+=ordering()
s+='''<section id="prenota" class="section booking"><div class="wrap split"><div><p class="eyebrow">IL TUO PROSSIMO MOMENTO FELICE</p><h2>Un tavolo ti aspetta.<br><em>O una pizza da portare via.</em></h2><p>Scegli come goderti Sorriso. Compila la richiesta e inviala al nostro staff su WhatsApp.</p><p>La prenotazione è confermata solo quando ricevi la nostra risposta.</p><a class="text-link" href="tel:+393455834226">Preferisci chiamare? 345 583 4226 ↗</a></div><form id="booking-form" class="booking-form"><div class="service-tabs" aria-label="Tipo di prenotazione"><button type="button" data-service="tavolo" aria-pressed="true">Un tavolo</button><button type="button" data-service="asporto" aria-pressed="false">Da asporto</button></div><input type="hidden" name="servizio" value="tavolo"><div class="form-grid"><label>Il tuo nome<input name="nome" autocomplete="name" required maxlength="80" placeholder="Come ti chiami?"></label><label>Telefono<input name="telefono" type="tel" autocomplete="tel" required pattern="[+0-9 ()-]{7,20}" placeholder="Il tuo numero"></label><label>Data<input name="data" type="date" required></label><label>Orario<select name="ora" required><option value="">Scegli l’orario</option><option>18:00</option><option>18:30</option><option>19:00</option><option>19:30</option><option>20:00</option><option>20:30</option><option>21:00</option><option>21:30</option><option>22:00</option><option>22:30</option></select></label><label id="people-field">Persone<select name="persone"><option>2 persone</option><option>1 persona</option><option>3 persone</option><option>4 persone</option><option>5 persone</option><option>6 persone</option><option>7 persone</option><option>8 persone</option><option>Più di 8 persone</option></select></label><label class="wide"><span id="note-label">Vuoi aggiungere qualcosa? (facoltativo)</span><textarea name="note" rows="3" maxlength="1200" placeholder="Un’occasione speciale, una preferenza…"></textarea></label></div><p class="fine">I dati del modulo non vengono salvati su questo sito. Il pulsante prepara un messaggio su WhatsApp: sarai tu a inviarlo al locale.</p><button class="button full" type="submit">Prepara richiesta di prenotazione ↗</button><p id="form-message" role="status"></p><a id="send-request" class="button full" hidden target="_blank" rel="noopener">Apri WhatsApp e invia ↗</a></form></div></section>'''
s+=f'''<section id="sedi" class="section wrap split"><div><p class="eyebrow">LE NOSTRE SEDI</p><h2>Il tuo Sorriso,<br>a <em>Roma.</em></h2><p>Ci trovi a San Basilio, in Via Sarnano.<br>Un posto per la tua prossima pizza in compagnia.</p><div class="address"><h3>Via Sarnano</h3><p>Via Sarnano 4 · 00156 Roma<br><a href="tel:+393455834226">345 583 4226</a></p><p>Martedì – domenica · 18:00–23:00<br>Lunedì · chiuso</p></div><div class="actions"><a class="button" href="{maps}" target="_blank" rel="noopener">Come raggiungerci ↗</a><a class="text-link" href="#prenota">Prenota un tavolo</a></div></div><div class="location-map"><iframe title="Google Maps — Sorriso Bistrot, Via Sarnano 4, Roma" src="https://www.google.com/maps?q=Via%20Sarnano%204%2C%2000156%20Roma&amp;z=16&amp;output=embed" width="600" height="450" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><a href="{maps}" target="_blank" rel="noopener">Apri in Google Maps ↗<span>Via Sarnano 4 · Roma</span></a></div></section>'''
s+='''<section class="wrap faq"><p class="eyebrow">PRIMA DI VENIRE A TROVARCI</p><h2>Qualche risposta, <em>subito.</em></h2><details><summary>Dove mangiare pizza senza glutine a Roma San Basilio?</summary><p>Sorriso Bistrot si trova in Via Sarnano 4, a Roma. Nel menù trovi pizze classiche, speciali e gourmet con prezzi distinti per la versione gluten free.</p></details><details><summary>Il locale propone solo prodotti senza glutine?</summary><p>No, a Via Sarnano sono presenti anche pizze con impasto classico contenente glutine. Segnala celiachia e allergie allo staff e chiedi informazioni sulle preparazioni prima di ordinare.</p></details><details><summary>Come prenoto un tavolo o una pizza da asporto?</summary><p>Usa il modulo per preparare la richiesta su WhatsApp o chiama il 345 583 4226. Per l’asporto indica prodotti, quantità e impasti. Attendi sempre la conferma dello staff.</p></details><details><summary>Ci sono anche fritti e dolci senza glutine?</summary><p>Sì, il menù include antipasti e dolci gluten free. Consulta la pagina menù per prodotti, prezzi e allergeni e verifica le disponibilità con lo staff.</p></details></section></main>'''
schema={'@context':'https://schema.org','@type':'Restaurant','name':'Sorriso Bistrot','servesCuisine':['Pizza','Italiana','Senza glutine'],'telephone':'+393455834226','address':{'@type':'PostalAddress','streetAddress':'Via Sarnano 4','postalCode':'00156','addressLocality':'Roma','addressCountry':'IT'}}
s+='<script type="application/ld+json">'+json.dumps(schema,ensure_ascii=False)+'</script>'+footer()
(P/'index.html').write_text(s)
# Full menu: prerender products so content and prices are available without JavaScript.
s=head('Menù pizza senza glutine a Roma | Sorriso Bistrot','Consulta tutti i prodotti e i prezzi del menù Sorriso Bistrot: pizza gluten free e classica, fritti, calzoni, primi, dolci e bevande. Via Sarnano, Roma.')+nav()
s+='''<main id="contenuto"><section class="wrap menu-page-head"><p class="eyebrow">SORRISO BISTROT · VIA SARNANO, ROMA</p><h1>Segui il gusto.<br><em>Trova il tuo Sorriso.</em></h1><p>Il nostro menù, dal primo supplì all’ultimo dolce.<br>Prezzi distinti per pizza classica e senza glutine, ingredienti e allergeni sempre a portata di mano.</p><div class="actions"><a class="button" href="index.html#prenota">Prenota un tavolo ↗</a><a class="button outline" href="index.html?servizio=asporto#prenota">Ordina d’asporto ↗</a><a class="text-link" href="Sorriso-Menu-IT.pdf">Scarica il menù PDF ↓</a></div></section>'''+ordering()+'''<section class="wrap menu-catalog"><div class="catalog-tools"><label>Cerca nel menù<input id="search-menu" type="search" placeholder="Margherita, supplì, pistacchio…"></label><label>Categoria<select id="category"><option value="tutte">Tutte le categorie</option>'''
for cat in data:s+=f'<option value="{cat["id"]}">{esc(cat["t"])}</option>'
s+='''</select></label><label>Listino pizze<select id="price-mode"><option value="gf">Senza glutine</option><option value="classica">Classica (con glutine)</option></select></label></div><p class="fine">Il selettore cambia il prezzo delle preparazioni con doppio listino. Non è un filtro allergeni; per le bevande consulta le indicazioni GF.</p><p id="result-count" role="status"></p><p id="empty-menu" hidden>Nessun prodotto trovato. Prova un altro ingrediente o seleziona tutte le categorie.</p>'''
for cat in data:
    s+=f'<section class="menu-category" data-category="{cat["id"]}"><div class="category-heading"><h2>{esc(cat["t"])}</h2><span>{len(cat["items"]):02d} proposte</span></div><div class="product-grid">'
    for it in cat['items']:
        n=it['n'];d=it['d'];pc=it['pc'];pg=it['pg']
        s+=f'<article class="product" data-search="{esc((n+" "+d).lower())}">{ph(n)}<div class="product-copy"><h3>{esc(n)}</h3><p>{esc(d)}</p><p class="allergens">Allergeni: {esc(it["a"]) if it["a"] else "chiedere allo staff"}</p><div class="product-price"><b data-classica="{esc(pc)}" data-gf="{esc(pg or pc)}">{esc(pg or pc)}</b><span>{"senza glutine" if pg else ""}</span></div></div></article>'
    s+='</div></section>'
s+='''</section><section class="wrap menu-notes"><h2>Ingredienti e allergeni</h2><p>1 Glutine · 2 Crostacei · 3 Uova · 4 Pesce · 5 Arachidi · 6 Soia · 7 Latte · 8 Frutta a guscio · 9 Sedano · 10 Senape · 11 Sesamo · 12 Anidride solforosa e solfiti · 13 Lupino · 14 Molluschi.</p><p>L’impasto classico contiene glutine. Le indicazioni sono riprese dal menù fornito; in caso di celiachia o allergie chiedi conferma al personale prima di ordinare. Il menù di origine riporta la possibile presenza di tracce per contaminazione.</p><p>Extra: ingrediente €1 · salsiccia €1,50 · prosciutto €2 · cornicione ricotta €2 · senza lattosio €1,50 · impasto canapa bio €2. Verifica le varianti disponibili con il locale.</p><a class="button" href="index.html?servizio=asporto#prenota">Ordina d’asporto ↗</a></section></main>'''+footer()
(P/'menu.html').write_text(s)
print('Generated homepage and menu:',sum(len(x['items']) for x in data),'products')
